export const PAGE_LOADING = "PAGE_LOADING";

//GITHUB
export const GITHUB = "GITHUB";

//Router
export const ROUTER_HISTORY_PUSH = "ROUTER_HISTORY_PUSH";
export const ROUTER_HISTORY_SPLICE = "ROUTER_HISTORY_SPLICE";

//Route
export const ROUTE = "ROUTE";

//USER
export const SET_USER = "SET_USER";

//NAVIGATION
export const SET_NAVIGATION_MENU = "SET_NAVIGATION_MENU";

//MESSAGES
export const ADD_SUCCESS = "ADD_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";
export const ADD_WARNING = "ADD_WARNING";
export const REMOVE_WARNING = "REMOVE_WARNING";
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

//MEDIA_UPLOAD
export const ADD_MEDIA = "ADD_MEDIA";
export const MEDIA = "MEDIA";
export const REMOVE_MEDIA = "REMOVE_MEDIA";
export const MEDIA_UPLOAD_VISIBLE = "MEDIA_UPLOAD_VISIBLE";
export const MEDIA_UPLOAD_CALLBACK = "MEDIA_UPLOAD_CALLBACK";
export const MEDIA_UPLOAD_EXITCALLBACK = "MEDIA_UPLOAD_EXITCALLBACK";
export const MEDIA_UPLOAD_DATA = "MEDIA_UPLOAD_DATA";
export const MEDIA_UPLOAD = "MEDIA_UPLOAD";
export const MEDIA_UPLOAD_TYPE = "MEDIA_UPLOAD_TYPE";
export const MEDIA_UPLOAD_MULTIPLE = "MEDIA_UPLOAD_MULTIPLE";
export const MEDIA_UPLOAD_SELECTED = "MEDIA_UPLOAD_SELECTED";
export const MEDIA_UPLOAD_URL = "MEDIA_UPLOAD_URL";
export const MEDIA_UPLOAD_SCROLL = "MEDIA_UPLOAD_SCROLL";
